In [4]:
import numpy as np 
a = np.array([[1,1,1],[0,1,1],[0,0,1]])
b = np.array([[7,5,3],[0,7,5],[0,0,7]])
ab = a.dot(b)
ba = b.dot(a)
c = ab - ba
print(c)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [5]:
a = np.array([[-1,0,2],[0,1,0],[1,2,-1]])
a_2 = np.linalg.matrix_power(a, 2)
print(a_2)

[[ 3  4 -4]
 [ 0  1  0]
 [-2  0  3]]


In [6]:
a = np.matrix('3 0 7; -4 2 3; -1 1 2') 
b = np.matrix('1; 2; 4') 
c = a.dot(b) 
print(c)

[[31]
 [12]
 [ 9]]


In [8]:
a = np.matrix('2 4 5; 1 1 2; 2 4 3') 
det = np.linalg.det(a)
print("Визначник = ", det.round(1))

Визначник =  4.0


In [10]:
a = np.matrix('2 3 4 1; 1 2 3 4; 3 4 1 2; 4 1 2 3')
det = np.linalg.det(a)
print("Визначник = ", det.round(1))

Визначник =  -160.0


In [11]:
a = np.array([[2,5,7],[6,3,4],[5,-2,-3]])
inv = np.linalg.inv(a)
print('Обернена матриця : ',"\n", inv)

Обернена матриця :  
 [[  1.  -1.   1.]
 [-38.  41. -34.]
 [ 27. -29.  24.]]


In [12]:
a = np.array([[-2, 3, 1, -1],[3, 2, 1, 4],[1, 2, 3, 4],[0, 2, 3, 3]])
rank_a = np.linalg.matrix_rank(a)
print(rank_a)

3


In [13]:
a = np.array([[1,-4,0],[2,-3,1],[1,4,2]])
b = np.array([[-5],[-7],[-1]])
def kram(a,b):# метод Крамера
    det_a = np.linalg.det(a)
    if det_a != 0:
        a1 = np.matrix(a)
        a2 = np.matrix(a)
        a3 = np.matrix(a)
        a1[:, 0] = b
        a2[:, 1] = b
        a3[:, 2] = b
        x = np.linalg.det(a1)/det_a
        y =np.linalg.det(a2)/det_a
        z= np.linalg.det(a3)/det_a
        print('x=',x.round(1),'y=',y.round(1),'z=',z.round(1)) 
    else:
        print("Система немає розв'язків, оскільки визначник дорівнює 0 ")
    return(x,y,z)
kram(a,b)
print("Перевірка розв'язку : ","\n", np.linalg.solve(a,b).round(1))

x= -1.0 y= 1.0 z= -2.0
Перевірка розв'язку :  
 [[-1.]
 [ 1.]
 [-2.]]


In [14]:
a = np.array([[1,-4,0],[2,-3,1],[1,4,2]])
b = np.array([[-5],[-7],[-1]])
inv_a = np.linalg.inv(a)
x = inv_a.dot(b)
print('X=', x)
print("Перевірка розв'язання : ","\n", np.linalg.solve(a,b).round(1))

X= [[-1.]
 [ 1.]
 [-2.]]
Перевірка розв'язання :  
 [[-1.]
 [ 1.]
 [-2.]]


In [15]:
import random as rd
n = 5
m = 3
a = np.zeros((n, m), dtype=int)
for i in range(n): 
    for j in range(m):
        a[i][j] = rd.randint(1, 20)

print(a)

for i in range(n): 
    suma_row = 0
    for j in range(m):
        suma_row += a[i][j]
    average_row = suma_row / m
    print(f"Середнє значення {i+1} рядка: {(average_row).round(1)}")

for j in range(m): 
    suma_column = 0
    for i in range(n):
        suma_column += a[i][j]
    average_column = suma_column / n
    print(f"Середнє значення {j+1} стовпця: {(average_column).round(1)}")


[[19  2 20]
 [13 12  5]
 [12  1  5]
 [ 9 19  1]
 [13 20 16]]
Середнє значення 1 рядка: 13.7
Середнє значення 2 рядка: 10.0
Середнє значення 3 рядка: 6.0
Середнє значення 4 рядка: 9.7
Середнє значення 5 рядка: 16.3
Середнє значення 1 стовпця: 13.2
Середнє значення 2 стовпця: 10.8
Середнє значення 3 стовпця: 9.4
